### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by thatoddmailbox** [kritollm/chrome-extension-api-for-safari-and-firefox#1]
This API has no license, making it not possible to use in published extensions, due to copyright issues.

Is it possible to include an open-source license of some sort so that other extensions can use this API?

**Comment by kritollm** [comment]
Yes, I don't know how to do that, but I can google it.

**Comment by thatoddmailbox** [comment]
It's not hard! GitHub actually has [a page](http://choosealicense.com/) dedicated to helping you choose a license. 

(I personally use the MIT license, but it should be fine to use any of the licenses on that page. However, you might not want to use the GPL license because it requires everyone who uses your API to _also_ use the GPL license.)

**Comment by kritollm** [comment]
Take a look and see if it's ok now. I added Licence.txt

**Comment by thatoddmailbox** [comment]
You could move License.txt to the root folder (rather than in the `chromeAPIFirefox` and `chromeAPISafari` folders), but it is fine how you have it now.

Thanks!
